package testSwing;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vn.edu.vtc.bl.AccountBL;

import vn.edu.vtc.bl.ProductBL;
import vn.edu.vtc.persistance.Account;
import vn.edu.vtc.persistance.Product;
import vn.edu.vtc.pl.OrderService;
import vn.edu.vtc.pl.StaticFunctionService;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class ProductManagementForm extends javax.swing.JFrame {
        private List<Product> localGottenProductOnSession = new ArrayList<>();
        private ProductBL productBL = new ProductBL();
        private DefaultTableModel defaultTableModel = new DefaultTableModel();
        private Account account;

        /**
         * Creates new form ProductManagementForm
         */
        public ProductManagementForm(Account account) {
                initComponents();
                defaultTableModel.addColumn("Mã Sản Phẩm");
                defaultTableModel.addColumn("Tên Sản Phẩm");
                defaultTableModel.addColumn("Mô Tả");
                defaultTableModel.addColumn("Số Lượng");
                defaultTableModel.addColumn("Giá Bán");
                defaultTableModel.addColumn("Ghi chú");
                tblResultSearchTab1.setModel(defaultTableModel);
                tblResultSearchTab1.setComponentPopupMenu(popupListProductResultSearch);
                this.account = account;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                popupListProductResultSearch = new javax.swing.JPopupMenu();
                menuitemUpdateProduct = new javax.swing.JMenuItem();
                jComboBox3 = new javax.swing.JComboBox<>();
                jLabel1 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                tabProductInformation2 = new javax.swing.JTabbedPane();
                jPanel4 = new javax.swing.JPanel();
                tabProductInformationPanel2 = new javax.swing.JPanel();
                comboboxTypeSearch = new javax.swing.JComboBox<>();
                labelForKeywordSearch2 = new javax.swing.JLabel();
                txtKeyWord = new javax.swing.JTextField();
                btnSearch = new javax.swing.JButton();
                btnResetTab1 = new javax.swing.JButton();
                panelResultSearch = new javax.swing.JPanel();
                jScrollPaneResultSearch = new javax.swing.JScrollPane();
                tblResultSearchTab1 = new javax.swing.JTable();
                jPanel3 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jSeparator2 = new javax.swing.JSeparator();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                btnCheckExistProductId = new javax.swing.JButton();
                btnCheckExistNewName = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtDescription = new javax.swing.JTextArea();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                spNewQuantity = new javax.swing.JSpinner();
                txtNewProductId = new javax.swing.JTextField();
                txtNewName = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox<>();
                jLabel8 = new javax.swing.JLabel();
                spNewPrice = new javax.swing.JSpinner();
                jComboBox2 = new javax.swing.JComboBox<>();
                btnInsert = new javax.swing.JButton();
                btnCancleTab2 = new javax.swing.JButton();
                btnLogOuttab2 = new javax.swing.JButton();
                lbForCheckingExistNewProductId = new javax.swing.JLabel();
                lbForCheckingNewName = new javax.swing.JLabel();
                btnLogout = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();

                menuitemUpdateProduct.setText("Cập nhật thông tin sản phẩm");
                menuitemUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                menuitemUpdateProductActionPerformed(evt);
                        }
                });
                popupListProductResultSearch.add(menuitemUpdateProduct);

                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel1.setText("Quản Lý Sản Phẩm");

                comboboxTypeSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                comboboxTypeSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hình thức tìm kiếm",
                                "Tìm kiếm theo tên", "Tìm kiếm theo mã sản phẩm", " " }));
                comboboxTypeSearch.setBorder(null);
                comboboxTypeSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                comboboxTypeSearchActionPerformed(evt);
                        }
                });

                labelForKeywordSearch2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                labelForKeywordSearch2.setText("Nhập từ khóa :");

                txtKeyWord.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtKeyWordActionPerformed(evt);
                        }
                });

                btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnSearch.setText("Tìm Kiếm");
                btnSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSearchActionPerformed(evt);
                        }
                });

                btnResetTab1.setText("Làm mới");
                btnResetTab1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnResetTab1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout tabProductInformationPanel2Layout = new javax.swing.GroupLayout(
                                tabProductInformationPanel2);
                tabProductInformationPanel2.setLayout(tabProductInformationPanel2Layout);
                tabProductInformationPanel2Layout.setHorizontalGroup(tabProductInformationPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(tabProductInformationPanel2Layout.createSequentialGroup()
                                                .addGap(192, 192, 192)
                                                .addGroup(tabProductInformationPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(tabProductInformationPanel2Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(txtKeyWord)
                                                                                .addComponent(comboboxTypeSearch, 0,
                                                                                                284, Short.MAX_VALUE)
                                                                                .addComponent(labelForKeywordSearch2))
                                                                .addGroup(tabProductInformationPanel2Layout
                                                                                .createSequentialGroup()
                                                                                .addComponent(btnResetTab1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                87,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(136, 136, 136)
                                                                                .addComponent(btnSearch,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                96,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));
                tabProductInformationPanel2Layout.setVerticalGroup(tabProductInformationPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(tabProductInformationPanel2Layout.createSequentialGroup()
                                                .addContainerGap(11, Short.MAX_VALUE)
                                                .addComponent(comboboxTypeSearch,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)
                                                .addComponent(labelForKeywordSearch2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 21,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addGroup(tabProductInformationPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(btnSearch,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                29,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnResetTab1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(37, 37, 37)));

                panelResultSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản Phẩm",
                                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                                javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

                tblResultSearchTab1.setAutoCreateRowSorter(true);
                tblResultSearchTab1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                tblResultSearchTab1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

                }, new String[] { "Mã Sản Phẩm", "Tên Sản Phẩm", "Mô tả", "Số lượng", "Giá Bán", "Ghi chú" }) {
                        Class[] types = new Class[] { java.lang.String.class, java.lang.String.class,
                                        java.lang.String.class, java.lang.Integer.class, java.lang.String.class,
                                        java.lang.String.class };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                tblResultSearchTab1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
                tblResultSearchTab1.setAutoscrolls(false);
                tblResultSearchTab1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                tblResultSearchTab1.setUpdateSelectionOnSort(false);
                jScrollPaneResultSearch.setViewportView(tblResultSearchTab1);

                javax.swing.GroupLayout panelResultSearchLayout = new javax.swing.GroupLayout(panelResultSearch);
                panelResultSearch.setLayout(panelResultSearchLayout);
                panelResultSearchLayout.setHorizontalGroup(panelResultSearchLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPaneResultSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 682,
                                                Short.MAX_VALUE));
                panelResultSearchLayout.setVerticalGroup(panelResultSearchLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPaneResultSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 161,
                                                Short.MAX_VALUE));

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(jPanel4Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout
                                                .createSequentialGroup().addContainerGap()
                                                .addComponent(tabProductInformationPanel2,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(panelResultSearch, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
                                                                .addComponent(tabProductInformationPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(30, 30, 30).addComponent(panelResultSearch,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                tabProductInformation2.addTab("Thông tin sản phẩm", jPanel4);

                jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel2.setText("Thêm mới sản phẩm");

                jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel3.setText("Mã sản phẩm  :");

                jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel4.setText("Tên sản phẩm :");
                jLabel4.setMaximumSize(new java.awt.Dimension(62, 13));
                jLabel4.setMinimumSize(new java.awt.Dimension(62, 13));
                jLabel4.setPreferredSize(new java.awt.Dimension(62, 13));

                btnCheckExistProductId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnCheckExistProductId.setText("Kiểm tra");
                btnCheckExistProductId.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCheckExistProductIdActionPerformed(evt);
                        }
                });

                btnCheckExistNewName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnCheckExistNewName.setText("Kiểm tra");
                btnCheckExistNewName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCheckExistNewNameActionPerformed(evt);
                        }
                });

                txtDescription.setColumns(20);
                txtDescription.setRows(5);
                jScrollPane1.setViewportView(txtDescription);

                jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel5.setText("Mô tả            :");

                jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel6.setText("Số Lượng       :");

                spNewQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

                txtNewProductId.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtNewProductIdActionPerformed(evt);
                        }
                });

                txtNewName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtNewNameActionPerformed(evt);
                        }
                });

                jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel7.setText("Đơn vị :");

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lẻ" }));

                jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel8.setText("Giá bán          :");

                spNewPrice.setModel(new javax.swing.SpinnerNumberModel(1000, 1000, null, 1));

                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VND" }));

                btnInsert.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnInsert.setText("Thêm Sản Phẩm");
                btnInsert.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnInsertActionPerformed(evt);
                        }
                });

                btnCancleTab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnCancleTab2.setText("Hủy");

                btnLogOuttab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnLogOuttab2.setText("Đăng Xuất");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(jPanel3Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup().addGap(25, 25, 25)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addGroup(jPanel3Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(jLabel4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                102,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                102,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel5,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                102,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(jPanel3Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addGroup(jPanel3Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                .addComponent(txtNewProductId,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                326,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(txtNewName))
                                                                                                                                .addGroup(jPanel3Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addGroup(jPanel3Layout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addComponent(jLabel7,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                59,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                                .addComponent(jComboBox1,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                100,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                .addComponent(jScrollPane1,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                326,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addGroup(jPanel3Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(btnCheckExistNewName)
                                                                                                                                .addComponent(btnCheckExistProductId))
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                39,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addGroup(jPanel3Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                .addComponent(lbForCheckingNewName,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                71,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(lbForCheckingExistNewProductId,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)))
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(226, 226,
                                                                                                                                226)
                                                                                                                .addComponent(btnInsert))))
                                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addGroup(jPanel3Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(jLabel8,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                102,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel6,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                102,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(spNewQuantity,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                86,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(jComboBox2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                77,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addComponent(spNewPrice,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                86,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(btnCancleTab2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                106,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
                                                .createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel3Layout.createSequentialGroup()
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                190,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(jPanel3Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(339, 339,
                                                                                                                                                339)
                                                                                                                                .addComponent(btnLogOuttab2,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                110,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addContainerGap())
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel3Layout.createSequentialGroup()
                                                                                                .addComponent(jSeparator2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                192,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(281, 281,
                                                                                                                281)))));
                jPanel3Layout.setVerticalGroup(jPanel3Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                39,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtNewProductId,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                31,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(btnCheckExistNewName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                32,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lbForCheckingExistNewProductId,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                28,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                24,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtNewName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                30,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnCheckExistProductId,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                32,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lbForCheckingNewName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                32,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                22,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel8,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                30,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(spNewPrice,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                jPanel3Layout.createSequentialGroup()
                                                                                                .addGap(3, 3, 3)
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel7,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                27,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jComboBox1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                28,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                25,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(spNewQuantity,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                25,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jComboBox2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(btnInsert,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnCancleTab2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(btnLogOuttab2, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)));

                tabProductInformation2.addTab("Thêm Mới Sản Phẩm", jPanel3);

                btnLogout.setText("Đăng Xuất");
                btnLogout.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLogoutActionPerformed(evt);
                        }
                });

                btnBack.setText("< Trở Lại");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(tabProductInformation2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                699,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                                .addGap(16, 16, 16)
                                                                                                .addComponent(btnBack,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                97,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jLabel1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                211,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(132, 132, 132)
                                                                                                .addComponent(btnLogout,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                119,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup().addGap(212, 212, 212)
                                                                .addComponent(jSeparator1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                255,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                29,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnLogout,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tabProductInformation2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 465,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap()));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                ManagerForm managerForm = new ManagerForm(account);
                managerForm.setVisible(true);
                this.dispose();
        }// GEN-LAST:event_btnBackActionPerformed

        private void menuitemUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuitemUpdateProductActionPerformed
                // TODO add your handling code here:
                int selected = JOptionPane.showConfirmDialog(this, "Cập Nhật Sản Phẩm?");
                if (selected == 0) {
                        // yes
                        int useRow = tblResultSearchTab1.getSelectedRow();
                        if (useRow == -1) {
                                JOptionPane.showMessageDialog(this, "Vui Lòng chọn sản phẩm !",
                                                "Cập Nhật Sản Phẩm", JOptionPane.ERROR_MESSAGE);
                        } else {
                                String productId = String.valueOf(tblResultSearchTab1.getValueAt(useRow, 0));
                                UpdateProductForm updateProductForm = new UpdateProductForm(productId);
                                updateProductForm.setVisible(true);

                        }
                }
        }// GEN-LAST:event_menuitemUpdateProductActionPerformed

        private void btnResetTab1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetTab1ActionPerformed
                // TODO add your handling code here:
                txtKeyWord.setText("");
                defaultTableModel.setRowCount(0);
        }// GEN-LAST:event_btnResetTab1ActionPerformed

        private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLogoutActionPerformed
                // TODO add your handling code here:
                Login login = new Login();
                login.setVisible(true);
                this.dispose();
        }// GEN-LAST:event_btnLogoutActionPerformed

        private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInsertActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnInsertActionPerformed

        private void txtNewNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNewNameActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtNewNameActionPerformed

        private void btnCheckExistNewNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCheckExistNewNameActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnCheckExistNewNameActionPerformed

        private void btnCheckExistProductIdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCheckExistProductIdActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnCheckExistProductIdActionPerformed

        private void txtNewProductIdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNewProductIdActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtNewProductIdActionPerformed

        private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
                if (comboboxTypeSearch.getSelectedItem().equals("Hình thức tìm kiếm")) {
                        JOptionPane.showMessageDialog(this, "Vui Lòng chọn Hình thức tìm kiếm !", "Tìm kiếm sản phẩm",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                }
                if (comboboxTypeSearch.getSelectedItem().equals("Tìm kiếm theo tên")) {
                        String productName = txtKeyWord.getText();
                        System.out.println(productName);
                        if (productName == null) {
                                JOptionPane.showMessageDialog(this, "Vui Lòng nhập mã sản phẩm !", "Tìm kiếm sản phẩm",
                                                JOptionPane.ERROR_MESSAGE);
                                return;
                        }
                        boolean checkExistOnLocal = false;
                        Product product = new Product();

                        for (Product productLoop : localGottenProductOnSession) {
                                if (productLoop.getName().equals(productName)) {
                                        product = productLoop;
                                        checkExistOnLocal = true;
                                        break;
                                }
                        }
                        if (!checkExistOnLocal) {
                                product = productBL.getByName2(productName);
                                if (product != null) {
                                        localGottenProductOnSession.add(product);
                                }
                        }
                        if (product == null) {
                                JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm nào !",
                                                "Tìm kiếm sản phẩm", JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        if (product != null) {

                                defaultTableModel.setRowCount(0);

                                for (Product productLoop : localGottenProductOnSession) {
                                        if (productLoop.equals(product)) {
                                                defaultTableModel.addRow(new Object[] { productLoop.getProductId(),
                                                                productLoop.getName(), productLoop.getLeftQuantity(),
                                                                OrderService.printPrice(productLoop.getPrice()) });
                                        }

                                }

                        } else {
                                JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm nào !",
                                                "Tìm kiếm sản phẩm", JOptionPane.ERROR_MESSAGE);
                                return;
                        }
                        return;
                }
                String productId = txtKeyWord.getText();
                if (productId == null) {
                        JOptionPane.showMessageDialog(this, "Vui Lòng nhập mã sản phẩm !", "Tìm kiếm sản phẩm",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                }
                if (comboboxTypeSearch.getSelectedItem().equals("Tìm kiếm theo mã sản phẩm")) {
                        boolean checkExistOnLocal = false;
                        Product product = new Product();
                        for (Product productLoop : localGottenProductOnSession) {
                                if (productLoop.getProductId().equals(productId)) {
                                        product = productLoop;
                                        checkExistOnLocal = true;
                                        break;
                                }
                        }
                        if (!checkExistOnLocal) {
                                product = productBL.getById(productId);
                                if (product != null) {
                                        localGottenProductOnSession.add(product);
                                }
                        }
                        if (product != null) {

                                defaultTableModel.setRowCount(0);
                                String description = null;
                                for (Product productLoop : localGottenProductOnSession) {
                                        if (productLoop.equals(product)) {
                                                description = productLoop.getDescription();
                                                if (description != null) {
                                                        defaultTableModel.addRow(new Object[] {
                                                                        productLoop.getProductId(),
                                                                        productLoop.getName(), description,
                                                                        productLoop.getLeftQuantity(),
                                                                        OrderService.printPrice(productLoop.getPrice()),
                                                                        productLoop.getCalculationUnit() });

                                                } else {
                                                        defaultTableModel.addRow(new Object[] {
                                                                        productLoop.getProductId(),
                                                                        productLoop.getName(), "",
                                                                        productLoop.getLeftQuantity(),
                                                                        OrderService.printPrice(productLoop.getPrice()),
                                                                        productLoop.getCalculationUnit() });
                                                }
                                        }
                                }

                        } else {
                                JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm nào !",
                                                "Tìm kiếm sản phẩm", JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                }

        }// GEN-LAST:event_btnSearchActionPerformed

        private void txtKeyWordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtKeyWordActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtKeyWordActionPerformed

        private void comboboxTypeSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboboxTypeSearchActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_comboboxTypeSearchActionPerformed

        private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextField2ActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel. For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(ProductManagementForm.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(ProductManagementForm.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(ProductManagementForm.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(ProductManagementForm.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                Account account = new AccountBL().login("Nguyenquyetthang",
                                                StaticFunctionService.getMd5("Thangnguyenquyet123"));
                                new ProductManagementForm(account).setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnCancleTab2;
        private javax.swing.JButton btnCheckExistNewName;
        private javax.swing.JButton btnCheckExistProductId;
        private javax.swing.JButton btnInsert;
        private javax.swing.JButton btnLogOuttab2;
        private javax.swing.JButton btnLogout;
        private javax.swing.JButton btnResetTab1;
        private javax.swing.JButton btnSearch;
        private javax.swing.JComboBox<String> comboboxTypeSearch;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JComboBox<String> jComboBox2;
        private javax.swing.JComboBox<String> jComboBox3;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPaneResultSearch;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JLabel labelForKeywordSearch2;
        private javax.swing.JLabel lbForCheckingExistNewProductId;
        private javax.swing.JLabel lbForCheckingNewName;
        private javax.swing.JMenuItem menuitemUpdateProduct;
        private javax.swing.JPanel panelResultSearch;
        private javax.swing.JPopupMenu popupListProductResultSearch;
        private javax.swing.JSpinner spNewPrice;
        private javax.swing.JSpinner spNewQuantity;
        private javax.swing.JTabbedPane tabProductInformation2;
        private javax.swing.JPanel tabProductInformationPanel2;
        private javax.swing.JTable tblResultSearchTab1;
        private javax.swing.JTextArea txtDescription;
        private javax.swing.JTextField txtKeyWord;
        private javax.swing.JTextField txtNewName;
        private javax.swing.JTextField txtNewProductId;
        // End of variables declaration//GEN-END:variables
}
