package testSwing;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import vn.edu.vtc.bl.ProductBL;
import vn.edu.vtc.persistance.Product;
import vn.edu.vtc.pl.OrderService;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class ProductManagementForm extends javax.swing.JFrame {
    private List<Product> localGottenProductOnSession= new ArrayList<>();
    private ProductBL productBL=new ProductBL();
    private DefaultTableModel defaultTableModel=new DefaultTableModel();
    /**
     * Creates new form ProductManagementForm
     */
    public ProductManagementForm() {
        initComponents();
        defaultTableModel.addColumn("Mã Sản Phẩm");
        defaultTableModel.addColumn("Tên Sản Phẩm");
        defaultTableModel.addColumn("Mô Tả");
        defaultTableModel.addColumn("Số Lượng");
        defaultTableModel.addColumn("Giá Bán");
        defaultTableModel.addColumn("Nhà Cung Cấp");
        defaultTableModel.addColumn("Ghi chú");
        tblResultSearchTab1.setModel(defaultTableModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popuptblResultSearch = new javax.swing.JPopupMenu();
        updateProduct = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tabProductInformation = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tabProductInformationPanel = new javax.swing.JPanel();
        comboboxTypeSearch = new javax.swing.JComboBox<>();
        labelForKeywordSearch = new javax.swing.JLabel();
        txtKeyWord = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        panelResultSearch = new javax.swing.JPanel();
        jScrollPaneResultSearch = new javax.swing.JScrollPane();
        tblResultSearchTab1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();

        updateProduct.setText("Cập nhật thông tin sản phẩm");
        popuptblResultSearch.add(updateProduct);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Quản Lý Sản Phẩm");

        comboboxTypeSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hình thức tìm kiếm", "Tìm kiếm theo tên", "Tìm kiếm theo mã sản phẩm", "Tìm kiếm theo giá sản phẩm" }));
        comboboxTypeSearch.setBorder(null);
        comboboxTypeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxTypeSearchActionPerformed(evt);
            }
        });

        labelForKeywordSearch.setText("Nhập từ khóa :");

        txtKeyWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeyWordActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabProductInformationPanelLayout = new javax.swing.GroupLayout(tabProductInformationPanel);
        tabProductInformationPanel.setLayout(tabProductInformationPanelLayout);
        tabProductInformationPanelLayout.setHorizontalGroup(
            tabProductInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProductInformationPanelLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(tabProductInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKeyWord)
                    .addGroup(tabProductInformationPanelLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelForKeywordSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxTypeSearch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        tabProductInformationPanelLayout.setVerticalGroup(
            tabProductInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProductInformationPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(comboboxTypeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelForKeywordSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelResultSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        tblResultSearchTab1.setAutoCreateRowSorter(true);
        tblResultSearchTab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Mô tả", "Số lượng", "Giá Bán", "Nhà cung cấp", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblResultSearchTab1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblResultSearchTab1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblResultSearchTab1.setUpdateSelectionOnSort(false);
        jScrollPaneResultSearch.setViewportView(tblResultSearchTab1);

        javax.swing.GroupLayout panelResultSearchLayout = new javax.swing.GroupLayout(panelResultSearch);
        panelResultSearch.setLayout(panelResultSearchLayout);
        panelResultSearchLayout.setHorizontalGroup(
            panelResultSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneResultSearch, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelResultSearchLayout.setVerticalGroup(
            panelResultSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultSearchLayout.createSequentialGroup()
                .addComponent(jScrollPaneResultSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabProductInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelResultSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabProductInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panelResultSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabProductInformation.addTab("Thông tin sản phẩm", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        tabProductInformation.addTab("Thêm Mới Sản Phẩm", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabProductInformation)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabProductInformation)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (comboboxTypeSearch.getSelectedItem().equals("Hình thức tìm kiếm")) {
            JOptionPane.showMessageDialog(this, "Vui Lòng chọn Hình thức tìm kiếm !", "Tìm kiếm sản phẩm", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (comboboxTypeSearch.getSelectedItem().equals("Tìm kiếm theo tên")) {
            //tìm kiếm theo tên
            JOptionPane.showMessageDialog(this, "Tìm kiếm theo tên");
            return;
        }
        String productId = txtKeyWord.getText();
        if (productId == null) {
            JOptionPane.showMessageDialog(this, "Vui Lòng nhập mã sản phẩm !", "Tìm kiếm sản phẩm", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (comboboxTypeSearch.getSelectedItem().equals("Tìm kiếm theo mã sản phẩm")) {
            boolean checkExistOnLocal=false;
            Product product =new Product();
            for (Product productLoop : localGottenProductOnSession) {
                if (productLoop.getProductId().equals(productId)){
                    product=productLoop;
                    checkExistOnLocal=true;
                    break;
                }
            }
            if (!checkExistOnLocal) {
                product= productBL.getById(productId);
                if (product!=null) {
                    localGottenProductOnSession.add(product);
                }
            }
            if (product != null) {
                
                defaultTableModel.setRowCount(0);
               
                for (Product productLoop : localGottenProductOnSession) {
                    if(productLoop.equals(product)){
                        defaultTableModel.addRow(new Object[]{productLoop.getProductId(), productLoop.getName(), productLoop.getLeftQuantity(), OrderService.printPrice(productLoop.getPrice())});
                    }
                    
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm nào !", "Tìm kiếm sản phẩm", JOptionPane.ERROR_MESSAGE);
                return;
            }

        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtKeyWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeyWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeyWordActionPerformed

    private void comboboxTypeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxTypeSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxTypeSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductManagementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboboxTypeSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPaneResultSearch;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelForKeywordSearch;
    private javax.swing.JPanel panelResultSearch;
    private javax.swing.JPopupMenu popuptblResultSearch;
    private javax.swing.JTabbedPane tabProductInformation;
    private javax.swing.JPanel tabProductInformationPanel;
    private javax.swing.JTable tblResultSearchTab1;
    private javax.swing.JTextField txtKeyWord;
    private javax.swing.JMenuItem updateProduct;
    // End of variables declaration//GEN-END:variables
}
